# Generated by Django 4.0.6 on 2022-08-02 18:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(default=0)),
                ('account_type', models.CharField(choices=[('f', 'fixed account'), ('c', 'current account')], max_length=30, null=True)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, null=True)),
                ('lastname', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True)),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=15, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('proile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('martialStatus', models.CharField(max_length=8, null=True)),
                ('employment_status', models.BooleanField(null=True)),
                ('signature', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=5, null=True)),
                ('receipt_date', models.DateTimeField()),
                ('bill_number', models.IntegerField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('receipt_file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('pin', models.CharField(default='', max_length=15)),
                ('isActive', models.BooleanField(null=True)),
                ('dateCreated', models.DateTimeField(default='')),
                ('currency', models.CharField(max_length=23, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_customer', to='walletapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.IntegerField(null=True)),
                ('transaction_amount', models.IntegerField(null=True)),
                ('transaction_type', models.CharField(choices=[('D', 'Deposite'), ('W', 'Withdrawal')], max_length=30, null=True)),
                ('transaction_charge', models.IntegerField(null=True)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime.now)),
                ('transactionreciept', models.CharField(max_length=8, null=True)),
                ('origin_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.account')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Thirdparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('transaction_account', models.IntegerField(null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('location', models.CharField(max_length=15, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('bonus', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('reward_points', models.IntegerField(null=True)),
                ('date_of_reward', models.DateTimeField()),
                ('recipient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(null=True)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification_recipient', to='walletapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(null=True)),
                ('loan_type', models.CharField(max_length=5, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('interest_rate', models.IntegerField(null=True)),
                ('payment_due_date', models.DateTimeField()),
                ('loan_balance', models.IntegerField(default=0)),
                ('loan_Term', models.IntegerField(null=True)),
                ('guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.thirdparty')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.CharField(max_length=30, null=True)),
                ('card_name', models.CharField(max_length=30, null=True)),
                ('card_number', models.IntegerField()),
                ('card_type', models.CharField(choices=[('C', 'Credit Card'), ('D', 'Debit Card')], max_length=30, null=True)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('card_status', models.CharField(max_length=30, null=True)),
                ('security_code', models.IntegerField(null=True)),
                ('issuer', models.CharField(choices=[('M', 'Master Card'), ('V', 'Visa Card')], max_length=30, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.account')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.wallet'),
        ),
    ]
