# Generated by Django 4.1 on 2022-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0002_remove_wallet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(max_length=23, null=True),
        ),
    ]
