# Generated by Django 4.0.6 on 2022-08-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0003_wallet_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='card',
            name='account',
        ),
        migrations.RemoveField(
            model_name='card',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='guarantor',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='origin_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.DeleteModel(
            name='Thirdparty',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
