# Generated by Django 4.0.6 on 2022-08-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0004_remove_account_wallet_remove_card_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(default=0)),
                ('account_type', models.CharField(choices=[('f', 'fixed account'), ('c', 'current account')], max_length=30, null=True)),
                ('balance', models.IntegerField(default=0)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.wallet')),
            ],
        ),
    ]
