# Generated by Django 4.0.6 on 2022-08-19 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0005_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.IntegerField(null=True)),
                ('transaction_amount', models.IntegerField(null=True)),
                ('transaction_type', models.CharField(choices=[('D', 'Deposite'), ('W', 'Withdrawal')], max_length=30, null=True)),
                ('transaction_charge', models.IntegerField(null=True)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime.now)),
                ('transactionreciept', models.CharField(max_length=8, null=True)),
                ('origin_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.account')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.wallet')),
            ],
        ),
    ]
