# Generated by Django 4.0.6 on 2022-08-19 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0006_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('issue_date', models.CharField(max_length=30, null=True)),
                ('card_name', models.CharField(max_length=30, null=True)),
                ('card_type', models.CharField(choices=[('C', 'Credit Card'), ('D', 'Debit Card')], max_length=30, null=True)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime.now)),
                ('card_status', models.CharField(max_length=30, null=True)),
                ('security_code', models.IntegerField(null=True)),
                ('issuer', models.CharField(choices=[('M', 'Master Card'), ('V', 'Visa Card')], max_length=30, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.account')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.wallet')),
            ],
        ),
    ]
