# Generated by Django 4.0.6 on 2022-08-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0007_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thirdparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_account', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=15, null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=15, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.account')),
            ],
        ),
    ]
