# Generated by Django 4.0.6 on 2022-08-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=5, null=True)),
                ('receipt_date', models.DateTimeField()),
                ('total_amount', models.IntegerField(null=True)),
                ('bill_number', models.IntegerField(null=True)),
                ('receipt_file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
