# Generated by Django 4.0.6 on 2022-08-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0010_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(null=True)),
                ('amount', models.IntegerField(default=0)),
                ('loan_type', models.CharField(max_length=5, null=True)),
                ('interest_rate', models.IntegerField(null=True)),
                ('loan_Term', models.IntegerField(null=True)),
                ('payment_due_date', models.DateTimeField()),
                ('loan_balance', models.IntegerField(default=0)),
                ('guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.thirdparty')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.wallet')),
            ],
        ),
    ]
