# Generated by Django 4.0.6 on 2022-08-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletapp', '0011_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('bonus', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('reward_points', models.IntegerField(null=True)),
                ('date_of_reward', models.DateTimeField()),
                ('recipient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletapp.account')),
            ],
        ),
    ]
